---
title: Data
description: We describe the sources of our data and the cleaning process.
toc: true
draft: false
---

## Data Sources

### Data Set 1: COMPAS Recitivism Dataset

#### Source

[Link To Dataset](https://github.com/propublica/compas-analysis)

This dataset was collected by ProPublica in 2013 and 2014 from the Broward County Sheriff’s Office in Florida and contains 11,757 individuals' COMPAS (Correctional Offender Management Profiling for Alternative Sanctions) scores. The COMPAS score is calculated via a computerized algorithm and is a metric commonly used by judges and officers to determine the likelihood of someone re-offending (recidivism). This data was originally collected by ProPublica to analyze and determine the presence of racial biases across the scores.

#### Layout

Within the GitHub repository there are several data files. For the purposes of our analysis, we will only be focusing on the `compas-scores-raw.csv` file which contains the raw data obtained by ProPublica via a public records request. This file contains 28 variables. Of these 28, we have determined that we will be focusing on the following 8:

-   **individual_ID:** The unique identifier for each individual
-   **Sex_Code_Text:** Indicates the individual's sex. We have re-coded this variable to `Sex` in the cleaned dataset.
-   **Ethnic_Code_Text**: Indicates a individual's ethnicity. Possible values are Caucasian, African-American, Hispanic, Other, Asian, and African-Am. We have recoded this variable to `Race` in the cleaned dataset.
-   **DateOfBirth:** Indicates the individual's date of birth
-   **Age:** The individual's age, calculated from DOB during data cleaning.
-   **RawScore:** The individual's raw COMPAS score. This is the raw score generated by the COMPAS algorithm and, in this dataset, ranges from -4.79 to 51.
-   **DecileScore:** The individual's decile compas score. This score is generated by ranking individuals by their raw scores, dividing this ranked list into ten equal parts (deciles), and assigning a score from 1 to 10 to each individual based on the decile they fall into, effectively categorizing them into relative risk levels.
-   **ScoreText:** The individual's categorized recidivism risk. Either Low, Medium, High, or N/A.

#### Cleaning and Loading

**Below is the data cleaning script**

```{r}
library(tidyverse)
library(dplyr)      # For attribute selection
library(lubridate)  # For calculating COMPAS person's age

compas_data <- read_csv(here::here("dataset", "compas-scores-raw.csv"))

## Clean the data

# Calculate age based on DateOfBirth and Screening_Date
# Convert date strings to Date objects
compas_data$DateOfBirth <- mdy(compas_data$DateOfBirth)
compas_data$Screening_Date <- mdy_hm(compas_data$Screening_Date)

compas_data$Age <- as.numeric(difftime(compas_data$Screening_Date, compas_data$DateOfBirth, units = "days") / 365.25)

compas_data_clean <- compas_data %>%
  select(Person_ID, Sex = Sex_Code_Text, Race = Ethnic_Code_Text, DateOfBirth, Age, RawScore, DecileScore, ScoreText) %>% 
  drop_na()

write_csv(compas_data_clean, file = here::here("dataset", "compas-scores-clean.csv"))

save(compas_data_clean, file = here::here("dataset/compas-scores-clean.RData"))
```

The above code:

1.  load the data from `compas-scores-raw.csv` in our `dataset` directory
2.  Then it tells R that `DateOfBirth` field follows `mm/dd/yyyy` format and `Screening_Date` follows `mm/dd/yyyy hh:mm` format using `mdy` and `mdy_hm` function from `lubridate` package.
3.  Using the difference in days between `DateOfBirth` and `Screening_Date`, we can calculate the age of that person. We then save the age to a field called `Age`.
4.  Then using `dplyr` package, we project on only those fields that we think is useful to us and drop any triples with na values.
5.  We save the clean data to `compas-scores-clean.csv` to our `dataset` directory.
