---
title: "Post 6"
author: ""
date: "2024-04-22"
date-modified: "2024-04-22"
draft: FALSE
---

## Continue Analysis on Combined Dataset 

The ROC curve's shape indicates that our logistic regression model has a good capability to discriminate between those individuals who were reincarcerated and those who were not. The curve's bow toward the top-left corner of the plot suggests that the model performs better than random chance at distinguishing between the two outcomes across a range of thresholds. And the AUC value of 0.6106, while above the threshold of 0.5, indicates that the model's discriminative ability is moderate.

The logistic regression models for Florida and Iowa reveal that sex and age are significant predictors of reincarceration in both states, with females having lower odds and younger individuals higher odds of reincarceration compared to males and older individuals, respectively. However, the influence of race varies between the states; in Florida, being Black significantly increases the odds of reincarceration, while in Iowa, this effect is present but to a lesser degree, and being Asian or Pacific Islander actually lowers the odds, a distinction not observed in Florida. Hispanic individuals have lower odds of reincarceration in Iowa, but this is not significant in Florida. These disparities underscore the need for state-specific criminal justice policies that address the unique sociodemographic factors influencing reincarceration in each state.

To further analyze on the difference in the recidivism of different racial groups between the two state, we generated a bar chart. The bar graph depicting reoffense rates by race in Iowa and Florida reveals notable disparities. In Iowa, the American Indian or Alaska Native group shows the highest reoffense proportion, surpassing that of Black individuals, who conversely represent the highest proportion in Florida. The reoffense rate for Black individuals in Florida is markedly elevated compared to that in Iowa. Hispanic and Other racial groups in both states reoffend at lower rates than the Black population, with relatively small differences between these groups across the states. The White and Asian or Pacific Islander populations have the lowest reoffense proportions in both states, with the latter group showing a slightly higher proportion in Florida than in Iowa. This variation in reoffense rates highlights the influence of racial and geographic factors on recidivism and suggests the need for tailored approaches to effectively reduce reoffending within diverse communities.

## Polishing Visualizations

To enhance the clarity and impact of our data visualizations and tables for the final project, we'll utilize features from ggpubr for refining figures, and explore gt and other resources provided by htmlwidgets.org for table formatting. Titles will be succinct yet descriptive, immediately informing readers about the content of the visualization. Captions will not only describe what is being presented but also highlight significant findings and how they relate to the overarching thesis. Annotations will be strategically placed to draw attention to key data points, trends, or anomalies that are crucial to our analysis. Highlights will be used to emphasize areas of particular interest, such as stark disparities or unexpected patterns. Through these enhancements, our visualizations and tables will not only be more aesthetically pleasing but also serve as effective storytelling tools that guide the viewer through our findings with greater ease and understanding.

