---
title: "Post 2: Project Update"
subtitle: "Data Background + Loading and Cleaning + Data for Equity"
author: ""
date: "2024-03-22"
date-modified: "2024-03-22"
draft: FALSE
---

After discussion, we decided to choose the data set about COMPAS Recidivism Racial Bias. We took time to investigate the data, so we found the original source about the data. Then, we did data loading and cleaning. At last, we read the article on Data for Equity Principals and thought about how the data could be applied on our data. And, we wrote several paragraphs about limitations of your analysis and the potential for abuse or misuse of the data.

# Data Loading and Cleaning Update

On COMPAS data:

-   Download and put raw data to data folder

-   Used dplyr package to select attributes that is useful to our project and get rid of those we don't need

-   Convert string date to date object with lubridate package.

-   From the date object, calculated each individual's age. This will be helpful later when we start using the second dataset, Iowa Probation Recidivism Status, which has age attribute.

-   Then we wrote the cleaned data to data folder.

## Data Equity

For the COMPAS Recidivism Racial Bias dataset, equitable data practices are relevant mainly from two points: Beneficence and Transparence. The beneficence principle demands that the collection, analysis, and dissemination of data on probation recidivism actively aim to benefit the individuals and communities represented in the data. For this dataset, adhering to beneficence involves being meticulous in how recidivism data are analyzed and presented. This means ensuring that the analysis does not inadvertently stigmatize individuals based on race, ethnicity, or any other demographic characteristic. It also involves considering the potential policy implications of the findings and framing results in a way that highlights systemic solutions rather than individual failings. Transparency is crucial in discussing the dataset's limitations and the context within which the data were collected and analyzed. Acknowledging the limitations in recidivism research, such as potential biases in the criminal justice system that affect who is under probation and the conditions of their supervision, is essential for responsible use of the data. Transparency about this dataset would involve openly discussing the potential for abuse or misuse of the data, such as the risk of the data being used to support policies that disproportionately affect marginalized communities. It also requires clear communication about the scope of the analysis, the assumptions made, and the measures taken to protect the privacy and dignity of individuals represented in the data. For instance, any analysis should be clear about its geographical and temporal scope, the definitions of success or failure in probation, and the inherent uncertainties in measuring and predicting recidivism. The analysis faces limitations that might not fully capture the complex factors influencing recidivism, such as access to support services and community reintegration programs. Additionally, there could be biases in data collection and reporting processes, reflecting systemic inequalities within the criminal justice system.
